language: node_js
node_js: '8'
os:
- linux
- osx
- windows
dist: xenial
osx_image: xcode10.1
cache:
  npm: true
  directories:
  - "$HOME/.cache/electron"
addons:
  apt:
    packages:
    - fakeroot
    - rpm
  homebrew:
    packages:
    - git-lfs
    update: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+/"
install:
- npm install
- npm update
script:
- npm run lint
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
before_script:
- npm i -g @electron-forge/cli
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then electron-forge make --targets @electron-forge/maker-deb; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir out/deb; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ls -l out/make; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp out/make/*.deb out/deb/; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then electron-forge make --targets @electron-forge/maker-rpm; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir out/rpm; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp out/make/*.rpm out/rpm/; fi
before_install:
- git lfs install
- git lfs pull
deploy:
  provider: releases
  api_key:
    secure: k3+JFsQcU+7h7ifNe1B3UdPLOgXGpgAyGqrFh87SqlmazSDOMVHKyX6nolAhczyftYSXQmZkR9tD2cGmtQ9+Zc+aLH0UKNBKLnDd+0j0j1mApLTSfjulfZXK587b2JjeIMjgxGzDIpvy5g+gCdMc36qF8fjyjfhwKnf1ypOESBWdWgAmm79LL3Onm+vRk4mO/0lj015WNXBOHyQQUd1Dc4OvI3YWM4mFUqJViwrK/HVZ0x3vln+yibNWtxksUITCmIoK9vWQZ/xvAXOnUIkm9IyKupZNhVC9lAP/GNsHkbG7uiyUlEDwsb1EYqQ79TWqS5vqMbc5rk4kncz+QlW+S/LFwV/qgNVmVmQfSX1PtBNJYOetbrHwJuLJd88RhKACFNUTEdeuToheKsLyDW0sHPdaEXO3nr1TKSATORLAAip3KDTZTxfXc9LFBs2m+prWWpfwXVvPC8j+0e3u9MsSA7Kvh1A6oPO72bc58a7ckqo39YxzUl6OFksGtT/wotVjVXRDgU3CA+wo6BRdGY/cirzAZqWKf+v8aqQrPX5Fhj54x7DgHfV8IIOlvcbEvIWF5VHvZvs3xI1el3r05hWgogbDsOEoGjzOFqLD5WzsusueKLYnnYQAISRXQui/picNb9bCC+812tT1myR3o/0TMA5IriunnV2TyE7Uik26FG4=
  file_glob: true
  file:
    - out/make/**/*.exe
    - out/rpm/**/*.rpm
    - out/deb/**/*.deb
    - out/make/**/*.dmg
  skip_cleanup: true
  on:
    repo: TunedChaos/smm2coursemanager-client
    tags: true
