language: node_js
node_js: "8"
os:
- linux
- osx
- windows
dist: xenial
osx_image: xcode10.1

cache:
  npm: true
  directories:
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

install:
- npm install
- npm update

script:
- npm run lint
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi

before_install:
- apt-get install build-essential curl file git
- sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
- test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
- test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
- test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
- echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
- brew install git-lfs

before_script:
- git lfs pull